dist: xenial
language: python
env:
  matrix:
    include:
        - python: 2.7
          env: TOXENV=py27
        - python: 3.5
          env: TOXENV=py35
        - python: 3.6
          env: TOXENV=py36
cache:
  directories:
    - $HOME/.cache/pip
install: pip install docutils tox
script: tox
